name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
    push:
      branches:
        - main

  # workflow_run:
  #   workflows: ["QnA CI"]
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Delete Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker rmi $DOCKER_USER/qna_api

    
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/qna_api:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f qna-fastapi-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: sudo docker run -it -d -p 8001:8001 -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --name=qna-fastapi-container $DOCKER_USER/qna_api:latest
