name: QnA CI

on:
 workflow_dispatch:
#    push:
#      branches:
#        - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install -r requirements/requirements.txt


      # - name: Execute build script
      #   run: |
      #     python -m pip install --upgrade build
      #     python -m build
      
      # - name: Move .whl file to API directory
      #   run: |
      #     mv dist/*whl qna_model_api/

      # - name: Build the Docker image for Fastapi app
      #   run: docker build . -f Dockerfile -t ${{ secrets.DOCKER_USER_NAME }}/qna_api:latest

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USER_NAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      
           
      # - name: Push the Docker Image
      #   run: docker push ${{ secrets.DOCKER_USER_NAME }}/qna_api

      - name: Build and Push Docker image for Angular app
        run: |
          cd UI
          docker build . -f Dockerfile -t ${{ secrets.DOCKER_USER_NAME }}/angular-api:latest 
          docker push ${{ secrets.DOCKER_USER_NAME }}/angular-api

      - name: Logout to Docker hub
        run: docker logout
